CREATE TABLE "movies" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "title" VARCHAR(255) NOT NULL,
                          "description" VARCHAR,
                          "duration" INT NOT NULL,
                          "price" NUMERIC(10, 2) NOT NULL
);

CREATE TABLE "halls" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                         "name" VARCHAR(255) NOT NULL,
                         "koef" FLOAT NOT NULL
);

CREATE TABLE "places" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "halls_id" BIGINT NOT NULL,
                          "row" INT NOT NULL,
                          "place" INT NOT NULL,
                          "koef" FLOAT NOT NULL
);

CREATE TABLE "session" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                           "datetime" timestamp NOT NULL,
                           "movie_id" BIGINT NOT NULL,
                           "hall_id" BIGINT NOT NULL,
                           "koef" FLOAT NOT NULL
);

CREATE TABLE "tickets" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                           "place_id" BIGINT NOT NULL,
                           "session_id" BIGINT NOT NULL
);

CREATE TABLE "orders" (
                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                          "pay" BOOL
);

CREATE TABLE "basket_item" (
                               "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                               "tickets_id" BIGINT UNIQUE NOT NULL,
                               "orders_id" BIGINT NOT NULL
);

CREATE UNIQUE INDEX ON "places" ("halls_id", "row", "place");

CREATE UNIQUE INDEX ON "tickets" ("place_id", "session_id");

ALTER TABLE "places" ADD FOREIGN KEY ("halls_id") REFERENCES "halls" ("id");

ALTER TABLE "session" ADD FOREIGN KEY ("hall_id") REFERENCES "halls" ("id");

ALTER TABLE "session" ADD FOREIGN KEY ("movie_id") REFERENCES "movies" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");

ALTER TABLE "tickets" ADD FOREIGN KEY ("session_id") REFERENCES "session" ("id");

ALTER TABLE "basket_item" ADD FOREIGN KEY ("orders_id") REFERENCES "orders" ("id");

ALTER TABLE "basket_item" ADD FOREIGN KEY ("tickets_id") REFERENCES "tickets" ("id");
