SELECT f.NAME AS film_name, SUM(price.PRICE) AS TOTAL_PROFIT
FROM TICKETS tickets
JOIN FILMS film ON tickets.FILM_ID = film.ID
JOIN SESSION_PLACE_PRICES spp ON tickets.SESSION_PLACE_PRICES_ID = spp.ID
JOIN PRICES price ON spp.PRICE_ID = price.ID
WHERE tickets.CLIENT_ID NOT NULL
GROUP BY film.ID
ORDER BY total_profit DESC
LIMIT 1;