SELECT film.NAME, SUM(ticket.PRICE) AS TOTAL_PROFIT
FROM FILMS film
JOIN SESSIONS sesion ON sesion.FILM_ID = film.ID
JOIN TICKET ticket ON ticket.SESSION_ID = sesion.ID
GROUP BY film.ID
ORDER BY TOTAL_PROFIT DESC LIMIT 1;
