<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240326110436 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE car_report ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE car_report ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE operation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE operation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE operation ALTER id SET DEFAULT operation_id_seq');
        $this->addSql('ALTER TABLE operation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE car_report ALTER id SET DEFAULT car_report_id_seq');
        $this->addSql('ALTER TABLE car_report ALTER id DROP IDENTITY');
    }
}
