FROM php:8.1-rc-fpm

ARG user
ARG uid

RUN apt-get update && \
    apt-get install -y git && \
    docker-php-ext-install sockets && \
    rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G users -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    mkdir -p /tmp/socket && \
    chown -R $user:$user /home/$user && \
    chown -R $user:$user /tmp/socket


USER $user

WORKDIR /var/www/app

VOLUME /var/www/app
VOLUME /tmp/socket

CMD ["php-fpm"]
