FROM php:8.1-rc-fpm

ARG user
ARG uid

RUN apt-get update && \
    apt-get install -y git libpq-dev p7zip && \
    docker-php-ext-install pdo pdo_pgsql pgsql sockets && \
    rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G users -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user


USER $user

WORKDIR /var/www/app

VOLUME /var/www/app

CMD ["php-fpm"]
