FROM php:8.2-rc-fpm

ARG user
ARG uid

# ставим необходимые для нормальной работы модули
RUN apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
	libpng-dev \
	libonig-dev \
	libzip-dev \
	libmemcached-dev \
    zlib1g-dev libssl-dev \
    && docker-php-ext-install -j$(nproc) iconv mbstring mysqli pdo_mysql zip \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && pecl install memcached \
    && docker-php-ext-enable memcached \
    && apt-get install -y libpq-dev \
    && apt-get install -y git \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && pecl install redis \
    && docker-php-ext-enable redis.so \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN useradd -G users -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

COPY php.ini /usr/local/etc/php/php.ini
#RUN echo "register_argc_argv=On" >> /usr/local/etc/php/php.ini
#RUN sed -i 's/register_argc_argv = Off/register_argc_argv = On/' /usr/local/etc/php/php.ini


USER $user

WORKDIR /var/www/app

VOLUME /var/www/app

CMD ["php-fpm"]
