help:
	@echo 'It is result`s home-work for lesson 02 php course of OTUS school'

setup:
	chmod +x ./sum.sh
	chmod +x ./most_popular_cities.sh

run-calc:
	./sum.sh 1.5 -7
	./sum.sh 1.5 7
	./sum.sh -1.5 -7.1
	./sum.sh 0 0
	./sum.sh 3 .14

run-calc-error-case-01:
	./sum.sh 1err0r 0

run-calc-error-case-02:
	./sum.sh 0 1.error

run-calc-error-case-03:
	./sum.sh 3 unvalid

run-calc-error-case-04:
	./sum.sh

run-sort:
	./most_popular_cities.sh
