-- Database: postgres

DROP TABLE IF EXISTS TicketSale;
DROP TABLE IF EXISTS ShowFilm;
DROP TABLE IF EXISTS TicketPrice ;
DROP TABLE IF EXISTS Show;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Film;


CREATE TABLE Film (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Room (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

CREATE TABLE Show (
  ID SERIAL PRIMARY KEY,
  TIME_START CHAR(5) NOT NULL
);

CREATE TABLE TicketPrice (
  ID SERIAL PRIMARY KEY,
  ID_ROOM INT NOT NULL,
  LINE INT NOT NULL,
  ID_SHOW INT NOT NULL,
  WEEKDAY INT NOT NULL,
  PRICE INT NOT NULL,
  FOREIGN KEY (ID_ROOM)
      REFERENCES Room (ID) ON UPDATE SET NULL ON DELETE CASCADE,
  FOREIGN KEY (ID_SHOW)
      REFERENCES Show (ID) ON UPDATE SET NULL ON DELETE CASCADE
);

CREATE TABLE ShowFilm (
  ID SERIAL PRIMARY KEY,
  ID_ROOM INT NOT NULL,
  ID_SHOW INT NOT NULL,
  ID_FILM INT NOT NULL,
  DATA TIMESTAMP ,
  FOREIGN KEY (ID_ROOM)
      REFERENCES Room (ID) ON UPDATE SET NULL ON DELETE CASCADE,
  FOREIGN KEY (ID_SHOW)
      REFERENCES Show (ID) ON UPDATE SET NULL ON DELETE CASCADE,
  FOREIGN KEY (ID_FILM)
      REFERENCES Film (ID) ON UPDATE SET NULL ON DELETE CASCADE
);

CREATE TABLE TicketSale (
  ID SERIAL PRIMARY KEY,
  ID_SHOW_FILM INT NOT NULL,
  LINE INT NOT NULL,
  PLACE INT NOT NULL,
  DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  FOREIGN KEY (ID_SHOW_FILM)
      REFERENCES ShowFilm (ID) ON UPDATE SET NULL ON DELETE CASCADE
);

