FROM php:8.2-cli

WORKDIR /var/www/otusphp.local

ENV COMPOSER_ALLOW_SUPERUSER=1

COPY ./composer.json .

RUN apt-get update && apt-get install -y \
    && docker-php-ext-install -j$(nproc) sockets \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && composer install

CMD ["php", "app.php", "client"]
